### ISSUE TITLE
Quarry crashing client/server with FTB Utilities installed

### ISSUE THREAD

**Issue by Desempregago** [TheUnderTaker11/KitchenSink#8]
Crashing with the onBlockBreak exception coming from FTB Utilities.

 java.lang.NullPointerException: Ticking block entity
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:51)
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:9)
	at net.minecraft.server.management.UserList.func_152692_d(SourceFile:97)
	at net.minecraft.server.management.PlayerList.func_152596_g(PlayerList.java:877)
	at com.feed_the_beast.ftbl.lib.util.ServerUtils.isOP(ServerUtils.java:213)
	at com.feed_the_beast.ftbu.ranks.Ranks.getRank(Ranks.java:74)
	at com.feed_the_beast.ftbu.api_impl.FTBUtilitiesAPI_Impl.getRank(FTBUtilitiesAPI_Impl.java:55)
	at com.feed_the_beast.ftbu.api_impl.FTBUtilitiesAPI_Impl.hasPermission(FTBUtilitiesAPI_Impl.java:78)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:84)
	at com.feed_the_beast.ftbu.FTBUPermissions.canModifyBlock(FTBUPermissions.java:140)
	at com.feed_the_beast.ftbu.api_impl.ClaimedChunkStorage.canPlayerInteract(ClaimedChunkStorage.java:91)
	at com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler.onBlockBreak(FTBUPlayerEventHandler.java:236)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_409_FTBUPlayerEventHandler_onBlockBreak_BreakEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at com.theundertaker11.kitchensink.ksblocks.quarry.KSTileEntityQuarryBlock.tryToMineBlock(KSTileEntityQuarryBlock.java:211)
	at com.theundertaker11.kitchensink.ksblocks.quarry.KSTileEntityQuarryBlock.func_73660_a(KSTileEntityQuarryBlock.java:86)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**Comment by Desempregago** [comment]
Seems like the Quarry bypass something like the Rank system from FTB Utilities

**Comment by TheUnderTaker11** [comment]
I don't know how FTB util handles any of that, but I'll go check my code and see what might be crashing it.

**Comment by Desempregago** [comment]
I had to disable FTB Utilities and install ChickenChunks temporarily only to use the Quarry, and IDK exactly how the Quarry works, the wiki says that the quarry mines down until it hits bedrock inside her/his radius, but I don't see/hear any blocks breaking, only entering the chest above the quarry :P

**Comment by TheUnderTaker11** [comment]
There is a lot more in the background such as making a fake player to break said blocks, allowing protection plugins to stop anyone from using my quarry to just place it near someones base and destroy the whole thing. Since you pointed this out though I noticed a few things I didn't do right in that area so I'm going through fixing a few. Hopefully FTB Utils won't throw that error after these changes.

**Comment by TheUnderTaker11** [comment]
I'm about to upload a beta version 1.20, get back to me if everything works as it should

**Comment by Desempregago** [comment]
Sorry for the delay, I was at the school taking tests..

I think the change didn't fix the issue..


java.lang.NullPointerException: Ticking block entity
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:51)
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:9)
	at net.minecraft.server.management.UserList.func_152692_d(SourceFile:97)
	at net.minecraft.server.management.PlayerList.func_152596_g(PlayerList.java:877)
	at com.feed_the_beast.ftbl.lib.util.ServerUtils.isOP(ServerUtils.java:213)
	at com.feed_the_beast.ftbu.ranks.Ranks.getRank(Ranks.java:74)
	at com.feed_the_beast.ftbu.api_impl.FTBUtilitiesAPI_Impl.getRank(FTBUtilitiesAPI_Impl.java:55)
	at com.feed_the_beast.ftbu.api_impl.FTBUtilitiesAPI_Impl.hasPermission(FTBUtilitiesAPI_Impl.java:78)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:84)
	at com.feed_the_beast.ftbu.FTBUPermissions.canModifyBlock(FTBUPermissions.java:140)
	at com.feed_the_beast.ftbu.api_impl.ClaimedChunkStorage.canPlayerInteract(ClaimedChunkStorage.java:91)
	at com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler.onBlockBreak(FTBUPlayerEventHandler.java:236)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_415_FTBUPlayerEventHandler_onBlockBreak_BreakEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at com.theundertaker11.kitchensink.ksblocks.quarry.KSTileEntityQuarryBlock.tryToMineBlock(KSTileEntityQuarryBlock.java:195)
	at com.theundertaker11.kitchensink.ksblocks.quarry.KSTileEntityQuarryBlock.func_73660_a(KSTileEntityQuarryBlock.java:87)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**Comment by TheUnderTaker11** [comment]
Hm since it IS a NPE, it is probably a mix of me doing quarrying different than other mod authors do (Not like there is a guide...) and them not doing a null check somewhere. I'll download it and do some testing, and make a report on their github, but that will take time.

Oh and the problem is probably with FTB Lib, not FTB Utils, although I'm not 100% sure. 
All that being said, I'm gonna start all this tomorrow, cause to be fully honest I really don't feel like starting that process today, cause there is a decent amount of things involved in that.

**Comment by Desempregago** [comment]
OK, take your time, don't need to rush, only if you want  :)

**Comment by TheUnderTaker11** [comment]
Just uploaded fixed version, no more crash and a fixed a few things in the background to make the quarry work better. (Might or might not notice user end but still)
